services:
  jenkins:
    image: "jenkins/jenkins:jdk17"
    container_name: jenkins
    restart: always
    ports:
      - "18080:8080"
      - "50000:50000"
    volumes:
      - /opt/app/jenkins:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
      - JAVA_OPTS="-Duser.timezone=Asia/Shanghai"